services:
  postgres:
    image: postgres:15
    container_name: unimobili_db
    environment:
      POSTGRES_DB: unimobili
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d unimobili"]
      interval: 5s
      timeout: 5s
      retries: 15
      start_period: 10s

  backend:
    build: ./api
    container_name: unimobili_backend
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/unimobili
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      # opcional, mas recomendado se você usa JWT_SECRET no application.properties
      JWT_SECRET: my-secret-key

volumes:
  postgres_data: